config/routes.rb
Rails.application.routes.draw do

  post "login" => "users#login"
  post "logout" => "users#logout"
  get "login" => "users#login_form"

  namespace :admin do
    resources :users do
    end  
  end

  namespace :user do
    get "tasks_for_calendar", to: "tasks#tasks"
    get "tasks/calendar"
    get "tasks/graph"
    resources :tasks do 
      patch :sort
    end
    resources :groups do 
      patch :sort
    end  
  end  

  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	belongs_to :group

	include RankedModel
	ranks :row_order

	validates :title, { presence: true }
	validates :status, { presence: true }
	validates :label, { presence: true }

	enum status: [:yet, :doing, :done]
	enum label: [:blue, :red, :yellow, :green]

	scope :alert, -> { where(due_date: Date.today - 30..Date.today + 2) }
	scope :desc, -> { order(created_at: :desc) }
	scope :get_by_label, -> (label) {
			where(label: label)
	}

	mount_uploader :file, FileUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, { presence: true, uniqueness: true }
  validates :email, { presence: true, uniqueness: true }
  validates :password, { presence: true }
  validates :role, { presence: true }

  enum role: [:user, :admin]

  has_many :tasks, dependent: :delete_all
  has_and_belongs_to_many :groups
  mount_uploader :image, ImageUploader

  def user_group_tasks
    Task.where(group_id: self.groups.ids)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin_layout"

  before_action :forbid_not_login_user
  before_action :forbid_not_admin_user

  def index
    @users = User.all
    @user = User.new
  end

  def create
    @users = User.all
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "アカウントを作成しました"
    else
      render :index
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザーを削除しました"
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "アカウントを編集しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :image, :role)
  end

  def forbid_not_admin_user
    if @current_user.user?
      redirect_to user_tasks_path, alert:"あなたは管理ユーザーではありません"
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :forbid_not_login_user

  def index
    if params[:label].present?
      @yet_tasks = @current_user.tasks.yet.get_by_label(params[:label])
      @doing_tasks = @current_user.tasks.doing.get_by_label(params[:label])
      @done_tasks = @current_user.tasks.done.get_by_label(params[:label])
    else
      @yet_tasks = @current_user.tasks.yet
      @doing_tasks = @current_user.tasks.doing
      @done_tasks = @current_user.tasks.done
    end
    @task = Task.new
    @label = params[:label]
  end

  def create
    @task = Task.new(task_params)
    @task.status = "yet"
    @task.user_id = @current_user.id
    if @task.save
      redirect_to tasks_path
    else 
      redirect_to tasks_path
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :body, :status, :due_date, :label)
  end
end

app/controllers/user/groups_controller.rb
class User::GroupsController < ApplicationController
  def index
    @group = Group.new
    @groups = @current_user.groups.rank(:row_order)
  end

  def create
    @group = Group.new(group_params)
    @groups = @current_user.groups
    if @group.save
      @current_user.groups << Group.find(@group.id)
      @current_user.save
      redirect_to user_groups_path, notice: "新しいグループを作成しました" 
    else 
      render :index
    end
  end

  def update 
    @group = Group.find(params[:id])
    @users = User.includes(:groups).where('groups.id' => @group.id)
    if @group.update(group_params)
      @group.save
      redirect_to user_groups_path, notice: "グループを編集しました"
    else 
      render :edit
    end
  end

  def edit
    @group = Group.find(params[:id])
    @users = User.includes(:groups).where('groups.id' => @group.id)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to user_groups_path, notice: "グループを削除しました"
  end

  def sort
    @group = Group.find_by(id: params[:group_id])
    @group.update(group_params)
    head :ok
  end

  private 
  def group_params
     params.require(:group).permit(:name, :row_order_position, { :user_ids => [] })
  end  
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :forbid_not_login_user
  PER = 5

  def index
    tasks_for_index(params)
    @task = Task.new
  end

  def create
    tasks_for_index(params)
    @task = Task.new(task_params)
    @task.user_id = @current_user.id
    @task.yet!
    if @task.save
      redirect_to user_tasks_path, notice: "新しいタスクを作成しました" 
    else 
      render :index
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      @task.save
      redirect_to user_tasks_path, notice: "タスクを編集しました"
    else 
      render :edit
    end    
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to user_tasks_path, notice: "タスクを削除しました"
  end

  def calendar
  end

  def tasks
    tasks_for_calendar = Task.where.not(due_date: nil).map do |task|
        { start: task.due_date, title: task.title }
    end    

    respond_to do |format|
      format.json { render json: tasks_for_calendar }
    end
  end

  def graph
    @tasks_data = @current_user.tasks.order('created_at ASC').group(:created_at).count
    @tasks = Task.rank(:row_order)
  end

  def sort
    @task = Task.find_by(id: params[:task_id])
    @task.update(task_params)
    head :ok
  end

  private
  def task_params
    params.require(:task).permit(:title, :body, :status, :due_date, :label, :group_id, :row_order_position, :file)
  end

  def tasks_for_index(params)
    @tasks = @current_user.user_group_tasks.or(@current_user.tasks)
    if params[:label].present?
      @yet_tasks = @tasks.yet.get_by_label(params[:label]).page(params[:yet_tasks_page]).per(PER).desc
      @doing_tasks = @tasks.doing.get_by_label(params[:label]).page(params[:doing_tasks_page]).per(PER).desc
      @done_tasks = @tasks.done.get_by_label(params[:label]).page(params[:done_tasks_page]).per(PER).desc
      @alert_tasks = @tasks.alert.get_by_label(params[:label]).page(params[:alert_tasks_page]).per(PER).desc
    else
      #@yet_tasks = @current_user.tasks.yet.page(params[:yet_tasks_page]).per(PER).desc
      @yet_tasks = @tasks.yet.page(params[:yet_tasks_page]).per(PER).desc
      @doing_tasks = @tasks.doing.page(params[:doing_tasks_page]).per(PER).desc
      @done_tasks = @tasks.done.page(params[:done_tasks_page]).per(PER).desc
      @alert_tasks = @tasks.alert.page(params[:alert_tasks_page]).per(PER).desc
    end
  end  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :forbid_not_login_user, only: [:edit, :update, :logout]
  before_action :forbid_login_user, only: [:login, :login_form]
  before_action :ensure_corrent_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_tasks_path
    else
      render :edit
    end
  end

  #session周り

  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_tasks_path, notice: "ログインしました！"
    else
      redirect_to login_path, alert: "メールアドレスかパスワードが違います"
    end
  end

  def login_form
  end

  def logout
    reset_session
    redirect_to login_path, notice: "ログアウトしました"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :image)
  end

  def ensure_corrent_user
    if session[:user_id] != params[:id].to_i
      redirect_to user_tasks_path, notice: "他のユーザーの情報は編集できません"
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/groups_helper.rb
module User::GroupsHelper
end

app/helpers/user/tasks_helper.rb
module User::TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/tasks/_tasks.html.erb
<table class="table">
  <% tasks.each do |task| %>
    <tr>
    <td> 
      <div class="tasks-index-task">
        <span class="image-wrapper">
          <%= image_tag task.user.image.url, class: "task-user-image" %>
        </span> 
        
        <div class="task-layer-top">
          <span class="task-label-color-box" style="background:<%= task.label %>;">
          </span>

          <% if task.due_date.present? %>
            <span class="task-due_date">
              <%= task.due_date %>
            </span>
          <% end %>
        </div> 

        <div class="task-title">
        <%= link_to(edit_user_task_path(task)) do %>
          <%= task.title %>
        <% end %>
        </div>

        
        <div class="task-layer-buttom">
          <span class="task-group-name">
            <% if task.group_id == 0 %>
            　<span>個人タスク</span>
            <% else %>
              <span><%= task.group.name %></span>
            <% end %>  
          </span>

          <span class="task-move-botton">
            <% if task.yet? %>
              <!-- 実行中へのボタン --> 
              <%= form_for [:user, task] do |f| %>
                <div class="form">
                  <%= f.hidden_field :status, value: "doing" %>
                  <div class="form-group">
                    <%= button_tag :type => "submit", :class => "btn btn-info btn-xs" do %> 
                      <i class="glyphicon glyphicon-play"></i>
                    <% end %> 
                  </div>
                </div>
              <% end %>
            <% elsif task.doing? %>
              <!-- 完了済みのボタン --> 
              <%= form_for [:user, task] do |f| %>
                <div class="form upgrade-button">
                  <%= f.hidden_field :status, value: "done" %>
                  <div class="form-group">
                    <%= button_tag :type => "submit", :class => "btn btn-primary btn-xs" do %> 
                      <i class="glyphicon glyphicon-play"></i>
                    <% end %>  
                  </div>
                </div>
              <% end %>
            <% elsif task.done? %>
              <div></div>
              <div class="form-group">
                <%= button_to(user_task_path(task), method: :delete, class: "btn btn-danger btn-xs") do %>
                  <i class="glyphicon glyphicon-remove"></i>
                <% end %>
              </div>  
            <% end %> 
          </span>
        </div>  
      </div>
    </td>
    </tr>
  <% end %>
</table>
<%= paginate tasks, param_name: param_name, :class => "pagenation-bar" %>

app/views/user/tasks/calendar.html.erb
<div class="container">
  <div id="calendar"></div>
</div>

app/views/user/tasks/edit.html.erb
<div class="container">
  <h1>タスクを編集してください</h1>
    <%= render partial: "partials/error_message", locals: { thing: @task } %>
    <%= @task.created_at %>
    <%= form_for [:user, @task] do |f| %>
    <div class="form">
      <div class="form-group">
        <%= f.text_field :title, :class => "form-control"  %>
      </div>
      <div class="form-group">
        <%= f.label :body, "詳細を書くことができます。" %>
        <%= f.text_area :body, :class => "form-control"  %>
      </div>
      <div class="form-group">
        <%= f.label :due_date, "締め切りは？" %><br>
        <%= f.date_select :due_date, :class => "form-control"  %>
      </div>
      <div class="form-group">
        <%= f.label :status, "ステータスを変更できます。" %><br>
        <%= f.select :status, [["未着手", "yet"], ["実行中", "doing"], ["完了済み", "done"]], :class => "form-control"  %>
      </div>
      <div class="form-group">
        <p>ラベルをつけましょう。</p>
        <%= f.radio_button :label, "red", :class => "hidden" %>
        <%= f.label :label_red, "red", :class => "label label-red" %>
        <%= f.radio_button :label, "yellow", :class => "hidden" %>
        <%= f.label :label_yellow, "yellow", :class => "label label-yellow" %>
        <%= f.radio_button :label, "green", :class => "hidden" %>
        <%= f.label :label_green, "green", :class => "label label-green" %>
        <%= f.radio_button :label, "blue", :class => "hidden" %>
        <%= f.label :label_blue, "blue", :class => "label label-blue" %>
      </div>
      <br><br><br><br><br>
      <p>ファイルを添付しますか？</p>
      <%= link_to 'download', "/uploads/task/file/#{@task.id}/#{@task.file_identifier}/", download: "test" %> 
      <% if @task.file.present? %>
        <%= image_tag @task.file.url, class: "current_user-image" %>
      <% end %>  
      <div class="form-group">
        <%= f.file_field :file, :class => "form-control" %>
      </div>
      <div class="form-group">
        <p>タスクをグループで共有しますか？</p>
        <%= f.collection_radio_buttons :group_id, @current_user.groups, :id, :name %>
      </div>
      <div class="form-group">
        <%= f.submit "更新", :class => "btn btn-success" %>
      </div>
      <% end %>
    </div>
    <%= link_to "タスクを削除", user_task_path(@task), method: :delete %><br>
    <%= link_to "一覧に戻る", user_tasks_path %>
</div>

app/views/user/tasks/graph.html.erb
<div class="container">
  <h1>自分の投稿の統計を見ることができます。</h1>
  <h3 class="graph-title">ラベルの統計</h3>
  <%= pie_chart @current_user.tasks.group(:label).count %>
  <h3 class="graph-title">ステータスの統計</h3>
  <%= pie_chart @current_user.tasks.group(:status).count, colors: ["gray", "blue", "black"] %>
</div>

<table class="table table-sortable">
  <% @tasks.each do |task| %>
    <tr class="item" data-target='{ "model_name": "<%= task.class.name.underscore %>", "update_url": "<%= user_task_sort_path(task) %>" }'>
    <td>
      <div class="task-title">
        <%= task.title %>
      </div>
    </td>
    </tr>
  <% end %>
</table>

app/views/user/tasks/index.html.erb
<div class="container">
  <!-- 新規登録フォーム -->
  <div class="task-new-form">
    <%= render partial: "partials/error_message", locals: { thing: @task } %>
    <%= form_for [:user, @task] do |f| %>
    <div class="form">
      <div class="form-inline">
        <%= f.text_field :title, :class => "form-control", style: "width: 800px;" %>
        <%= f.submit "投稿", :class => "btn btn-success" %>
      </div>
    </div>
    <% end %>
  </div>
  <br>

  <!-- ソートフォーム -->
  <div class="search-form">
    <%= form_tag(user_tasks_path, method: "get") do %>
      <%= select_tag :label, options_for_select(Task.labels), :include_blank => true %>
      <%= submit_tag "検索", :class => "btn btn-success" %>
    <% end %>
  </div>

  <div class="tables">
    <div class="table-wrapper">
      <p class="table-title">未着手のタスク</p>
      <div id="table1">
        <%= render :partial => 'tasks', locals: { tasks: @yet_tasks, param_name: "yet_tasks_page" } %>
      </div>
    </div>    
    <div class="table-wrapper">
      <p class="table-title">実行中のタスク</p>
      <div id="table2">
        <%= render :partial => 'tasks', locals: { tasks: @doing_tasks, param_name: "doing_tasks_page" } %>
      </div>
    </div>  
    <div class="table-wrapper">
      <p class="table-title">完了したタスク</p>
      <div id="table3">
        <%= render :partial => 'tasks', locals: { tasks: @done_tasks, param_name: "done_tasks_page" } %>
      </div>  
    </div>
    <div class="table-wrapper"> 
      <p class="table-title">終了期限が近いタスク</p> 
      <div id="table5">
        <%= render :partial => 'tasks', locals: { tasks: @alert_tasks, param_name: "alert_tasks_page" } %>
      </div>
    </div>
  </div>  
</div>