config/routes.rb
Rails.application.routes.draw do

  post "login" => "users#login"
  post "logout" => "users#logout"
  get "login" => "users#login_form"

  namespace :admin do
    resources :users do
    end  
  end

  namespace :user do
    get "tasks_for_calendar", to: "tasks#tasks"
    get "tasks/calendar"
    get "tasks/graph"
    resources :tasks do 
      patch :sort
    end
    resources :groups do 
      patch :sort
    end  
  end  

  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	belongs_to :group

	include RankedModel
	ranks :row_order

	validates :title, { presence: true }
	validates :status, { presence: true }
	validates :label, { presence: true }

	enum status: [:yet, :doing, :done]
	enum label: [:blue, :red, :yellow, :green]

	scope :alert, -> { where(due_date: Date.today - 30..Date.today + 2) }
	scope :desc, -> { order(created_at: :desc) }
	scope :get_by_label, -> (label) {
			where(label: label)
	}

	mount_uploader :file, FileUploader

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :forbid_not_login_user

  def index
    if params[:label].present?
      @yet_tasks = @current_user.tasks.yet.get_by_label(params[:label])
      @doing_tasks = @current_user.tasks.doing.get_by_label(params[:label])
      @done_tasks = @current_user.tasks.done.get_by_label(params[:label])
    else
      @yet_tasks = @current_user.tasks.yet
      @doing_tasks = @current_user.tasks.doing
      @done_tasks = @current_user.tasks.done
    end
    @task = Task.new
    @label = params[:label]
  end

  def create
    @task = Task.new(task_params)
    @task.status = "yet"
    @task.user_id = @current_user.id
    if @task.save
      redirect_to tasks_path
    else 
      redirect_to tasks_path
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :body, :status, :due_date, :label)
  end
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :forbid_not_login_user
  PER = 5

  def index
    tasks_for_index(params)
    @task = Task.new
  end

  def create
    tasks_for_index(params)
    @task = Task.new(task_params)
    @task.user_id = @current_user.id
    @task.yet!
    if @task.save
      redirect_to user_tasks_path, notice: "新しいタスクを作成しました" 
    else 
      render :index
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      @task.save
      redirect_to user_tasks_path, notice: "タスクを編集しました"
    else 
      render :edit
    end    
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to user_tasks_path, notice: "タスクを削除しました"
  end

  def calendar
  end

  def tasks
    tasks_for_calendar = Task.where.not(due_date: nil).map do |task|
        { start: task.due_date, title: task.title }
    end    

    respond_to do |format|
      format.json { render json: tasks_for_calendar }
    end
  end

  def graph
    @tasks_data = @current_user.tasks.order('created_at ASC').group(:created_at).count
    @tasks = Task.rank(:row_order)
  end

  def sort
    @task = Task.find_by(id: params[:task_id])
    @task.update(task_params)
    head :ok
  end

  private
  def task_params
    params.require(:task).permit(:title, :body, :status, :due_date, :label, :group_id, :row_order_position, :file)
  end

  def tasks_for_index(params)
    @tasks = @current_user.user_group_tasks.or(@current_user.tasks)
    if params[:label].present?
      @yet_tasks = @tasks.yet.get_by_label(params[:label]).page(params[:yet_tasks_page]).per(PER).desc
      @doing_tasks = @tasks.doing.get_by_label(params[:label]).page(params[:doing_tasks_page]).per(PER).desc
      @done_tasks = @tasks.done.get_by_label(params[:label]).page(params[:done_tasks_page]).per(PER).desc
      @alert_tasks = @tasks.alert.get_by_label(params[:label]).page(params[:alert_tasks_page]).per(PER).desc
    else
      #@yet_tasks = @current_user.tasks.yet.page(params[:yet_tasks_page]).per(PER).desc
      @yet_tasks = @tasks.yet.page(params[:yet_tasks_page]).per(PER).desc
      @doing_tasks = @tasks.doing.page(params[:doing_tasks_page]).per(PER).desc
      @done_tasks = @tasks.done.page(params[:done_tasks_page]).per(PER).desc
      @alert_tasks = @tasks.alert.page(params[:alert_tasks_page]).per(PER).desc
    end
  end  
  
end

app/helpers/user/tasks_helper.rb
module User::TasksHelper
end

app/views/tasks/edit.html.erb
<div class="container">
  <h1>タスクを編集してください</h1>
    <%= @task.created_at %>
    <%= form_for (@task) do |f| %>
    <div class="form">
      <div class="form-body">
        <%= f.text_field :title, :class => "form-control"  %>
      </div>
      <div class="form-body">
        <%= f.label :body, "詳細を書くことができます。" %>
        <%= f.text_area :body, :class => "form-control"  %>
      </div>
      <div class="form-body">
        <%= f.label :due_date, "締め切りは？" %><br>
        <%= f.date_select :due_date, :class => "form-control"  %>
      </div>
      <div class="form-body">
        <%= f.label :status, "ステータスを変更できます。" %><br>
        <%= f.select :status, [["未着手", "yet"], ["実行中", "doing"], ["完了済み", "done"]], :class => "form-control"  %>
      </div>
      <div class="form-body">
        <%= f.label :label, "ラベルをつけましょう。" %><br>
        <%= f.radio_button :label, "red" %>
        <%= f.label :label_red, "red", :class => "label label-red" %>
        <%= f.radio_button :label, "yellow" %>
        <%= f.label :label_yellow, "yellow", :class => "label label-yellow" %>
        <%= f.radio_button :label, "green" %>
        <%= f.label :label_green, "green", :class => "label label-green" %>
        <%= f.radio_button :label, "blue" %>
        <%= f.label :label_blue, "blue", :class => "label label-blue" %>
      </div>
      <br>
      <div class="form-body">
        <%= f.submit "更新", :class => "btn btn-success" %>
      </div>
      <% end %>
    </div>
    <%= link_to "タスクを削除", task_path(@task), method: :delete %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>This is Task-index page.</h1>
  <%= image_tag @current_user.image.url, class: "current_user-image" %>

  <!-- ソートフォーム -->
  <div class="search-form">
    <%= form_tag(tasks_path, method: "get") do %>
      <%= select_tag :label, options_for_select(Task.labels) %>
      <%= submit_tag "検索" %>
    <% end %>
  </div>

  <ul class="nav nav-tabs">
    <li><a href="#table1" data-toggle="tab">未着手<span class-"tasks-count"><%= @yet_tasks.size %></span></a></li>
    <li class="active"><a href="#table2" data-toggle="tab">実行中<span class-"tasks-count"><%= @doing_tasks.size %></span></a></li>
    <li><a href="#table3" data-toggle="tab">完了済み<span class-"tasks-count"><%= @done_tasks.size %></span></a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane" id="table1">
      <table class="table">
        <% @yet_tasks.each do |task| %>
          <tr>
          <td>
            <span class="label-color-box" style="background:<%= task.label %>;">
            </span>
            <%= link_to(edit_task_path(task)) do %>
              <div class="task-title">
                <%= task.title %>
              </div>
              <div class="task-due_date">
                <%= task.due_date %>
              </div>
            <% end %>

            <!-- 実行中へのボタン --> 
            <%= form_for(task) do |f| %>
              <div class="form">
                <div class="form-body">
                  <%= f.hidden_field :status, value: "doing" %>
                </div>
                <div class="form-body">
                  <%= f.submit "実行中へ", :class => "btn btn-success" %>  
                </div>
              </div>
            <% end %>

          </td>
          </tr>
        <% end %>
      </table>
    </div>  

    <div class="tab-pane active" id="table2">
      <table class="table">
        <% @doing_tasks.each do |task| %>
          <tr>
          <td>
            <span class="label-color-box" style="background:<%= task.label %>;">
            </span>
            <%= link_to(edit_task_path(task)) do %>
              <div class="task-title">
                <%= task.title %>
              </div>
              <div class="task-due_date">
                <%= task.due_date %>
              </div>
            <% end %>

            <!-- 実行中へのボタン --> 
            <%= form_for(task) do |f| %>
              <div class="form upgrade-button">
                <div class="form-body">
                  <%= f.hidden_field :status, value: "done" %>
                </div>
                <div class="form-body">
                  <%= f.submit "完了済みへ", :class => "btn btn-success" %>  
                </div>
              </div>
            <% end %>

          </td>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="tab-pane" id="table3">
      <table class="table">
        <% @done_tasks.each do |task| %>
          <tr>
          <td>
            <span class="label-color-box" style="background:<%= task.label %>;">
            </span>
            <%= link_to(edit_task_path(task)) do %>
              <div class="task-title">
                <%= task.title %>
              </div>
              <div class="task-due_date">
                <%= task.due_date %>
              </div>
            <% end %>
          </td>
          </tr>
        <% end %>
      </table>
    </div>  
  </div>

  <!-- 新規登録フォーム -->
  <div class="task-new-form">
    <%= form_for (@task) do |f| %>
    <div class="form">
      <div class="form-body">
        <%= f.text_field :title, :class => "form-control"  %>
      </div>
      <div class="form-body">
        <%= f.submit "投稿", :class => "btn btn-success" %>
      </div>
    </div>
    <% end %>
  </div>

</div>