config/routes.rb
Rails.application.routes.draw do

  post "login" => "users#login"
  post "logout" => "users#logout"
  get "login" => "users#login_form"

  namespace :admin do
    resources :users do
    end  
  end

  namespace :user do
    get "tasks_for_calendar", to: "tasks#tasks"
    get "tasks/calendar"
    get "tasks/graph"
    resources :tasks do 
      patch :sort
    end
    resources :groups do 
      patch :sort
    end  
  end  

  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, { presence: true, uniqueness: true }
  validates :email, { presence: true, uniqueness: true }
  validates :password, { presence: true }
  validates :role, { presence: true }

  enum role: [:user, :admin]

  has_many :tasks, dependent: :delete_all
  has_and_belongs_to_many :groups
  mount_uploader :image, ImageUploader

  def user_group_tasks
    Task.where(group_id: self.groups.ids)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin_layout"

  before_action :forbid_not_login_user
  before_action :forbid_not_admin_user

  def index
    @users = User.all
    @user = User.new
  end

  def create
    @users = User.all
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "アカウントを作成しました"
    else
      render :index
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザーを削除しました"
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "アカウントを編集しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :image, :role)
  end

  def forbid_not_admin_user
    if @current_user.user?
      redirect_to user_tasks_path, alert:"あなたは管理ユーザーではありません"
    end
  end

end

app/controllers/user/groups_controller.rb
class User::GroupsController < ApplicationController
  def index
    @group = Group.new
    @groups = @current_user.groups.rank(:row_order)
  end

  def create
    @group = Group.new(group_params)
    @groups = @current_user.groups
    if @group.save
      @current_user.groups << Group.find(@group.id)
      @current_user.save
      redirect_to user_groups_path, notice: "新しいグループを作成しました" 
    else 
      render :index
    end
  end

  def update 
    @group = Group.find(params[:id])
    @users = User.includes(:groups).where('groups.id' => @group.id)
    if @group.update(group_params)
      @group.save
      redirect_to user_groups_path, notice: "グループを編集しました"
    else 
      render :edit
    end
  end

  def edit
    @group = Group.find(params[:id])
    @users = User.includes(:groups).where('groups.id' => @group.id)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to user_groups_path, notice: "グループを削除しました"
  end

  def sort
    @group = Group.find_by(id: params[:group_id])
    @group.update(group_params)
    head :ok
  end

  private 
  def group_params
     params.require(:group).permit(:name, :row_order_position, { :user_ids => [] })
  end  
end

app/controllers/user/tasks_controller.rb
class User::TasksController < ApplicationController
  before_action :forbid_not_login_user
  PER = 5

  def index
    tasks_for_index(params)
    @task = Task.new
  end

  def create
    tasks_for_index(params)
    @task = Task.new(task_params)
    @task.user_id = @current_user.id
    @task.yet!
    if @task.save
      redirect_to user_tasks_path, notice: "新しいタスクを作成しました" 
    else 
      render :index
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      @task.save
      redirect_to user_tasks_path, notice: "タスクを編集しました"
    else 
      render :edit
    end    
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to user_tasks_path, notice: "タスクを削除しました"
  end

  def calendar
  end

  def tasks
    tasks_for_calendar = Task.where.not(due_date: nil).map do |task|
        { start: task.due_date, title: task.title }
    end    

    respond_to do |format|
      format.json { render json: tasks_for_calendar }
    end
  end

  def graph
    @tasks_data = @current_user.tasks.order('created_at ASC').group(:created_at).count
    @tasks = Task.rank(:row_order)
  end

  def sort
    @task = Task.find_by(id: params[:task_id])
    @task.update(task_params)
    head :ok
  end

  private
  def task_params
    params.require(:task).permit(:title, :body, :status, :due_date, :label, :group_id, :row_order_position, :file)
  end

  def tasks_for_index(params)
    @tasks = @current_user.user_group_tasks.or(@current_user.tasks)
    if params[:label].present?
      @yet_tasks = @tasks.yet.get_by_label(params[:label]).page(params[:yet_tasks_page]).per(PER).desc
      @doing_tasks = @tasks.doing.get_by_label(params[:label]).page(params[:doing_tasks_page]).per(PER).desc
      @done_tasks = @tasks.done.get_by_label(params[:label]).page(params[:done_tasks_page]).per(PER).desc
      @alert_tasks = @tasks.alert.get_by_label(params[:label]).page(params[:alert_tasks_page]).per(PER).desc
    else
      #@yet_tasks = @current_user.tasks.yet.page(params[:yet_tasks_page]).per(PER).desc
      @yet_tasks = @tasks.yet.page(params[:yet_tasks_page]).per(PER).desc
      @doing_tasks = @tasks.doing.page(params[:doing_tasks_page]).per(PER).desc
      @done_tasks = @tasks.done.page(params[:done_tasks_page]).per(PER).desc
      @alert_tasks = @tasks.alert.page(params[:alert_tasks_page]).per(PER).desc
    end
  end  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :forbid_not_login_user, only: [:edit, :update, :logout]
  before_action :forbid_login_user, only: [:login, :login_form]
  before_action :ensure_corrent_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_tasks_path
    else
      render :edit
    end
  end

  #session周り

  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_tasks_path, notice: "ログインしました！"
    else
      redirect_to login_path, alert: "メールアドレスかパスワードが違います"
    end
  end

  def login_form
  end

  def logout
    reset_session
    redirect_to login_path, notice: "ログアウトしました"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :image)
  end

  def ensure_corrent_user
    if session[:user_id] != params[:id].to_i
      redirect_to user_tasks_path, notice: "他のユーザーの情報は編集できません"
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/groups_helper.rb
module User::GroupsHelper
end

app/helpers/user/tasks_helper.rb
module User::TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <h1>他人の情報を編集できます。</h1>
  <h3>※パスワードは変更できません</h3>
  <%= render partial: "partials/error_message", locals: { thing: @user } %>
  <%= form_for [:admin, @user] do |f| %>
    <div class="form-group">
      <%= f.text_field :name, :class => "form-control", :placeholder => "Name" %>
    </div>
    <div class="form-group">
      <%= f.email_field :email, :class => "form-control", :placeholder => "Email" %>
    </div>
    <div class="form-group">
      <%= f.file_field :image, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :role_user, "権限なし" %>
      <%= f.radio_button :role, "user" %>
      <%= f.label :role_admin, "権限あり" %>
      <%= f.radio_button :role, "admin" %>
    </div>  
    <div class="form-group">
      <%= f.submit "変更", :class => "btn btn-success" %>
    </div>
  <% end %>
  <% if @current_user.id != @user.id %>
    <%= link_to "このユーザーを削除", admin_user_path(@user), method: :delete %><br>
  <% end %>  
  <%= link_to "一覧に戻る", admin_users_path %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h1>This is admin home.</h1>
  <h2>ユーザー一覧</h2>
  <table class="table table-bordered">
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.image.url, class: "current_user-image" %>
          <%= link_to(user.name, edit_admin_user_path(user)) %>
        </td>
      </tr>
    <% end %>
  </table>
  <h2>新しいユーザーを作ることができます。</h2>
  <h4>※パスワードは本人に変更させてください。</h4>
  <div class="container">
    <%= render partial: "partials/error_message", locals: { thing: @user } %>
    <%= form_for [:admin, @user] do |f| %>
    <div class="form-group">
      <%= f.text_field :name, :class => "form-control", :placeholder => "Name" %>
    </div>
    <div class="form-group">
      <%= f.email_field :email, :class => "form-control", :placeholder => "Email" %>
    </div>
    <div class="form-group">
      <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>
    </div>
    <div class="form-group">
      <%= f.submit "登録", :class => "btn btn-success" %>
    </div>
    <% end %>
  </div>
</div>  