config/routes.rb
Rails.application.routes.draw do

  post "login" => "users#login"
  post "logout" => "users#logout"
  get "login" => "users#login_form"

  namespace :admin do
    resources :users do
    end  
  end

  namespace :user do
    get "tasks_for_calendar", to: "tasks#tasks"
    get "tasks/calendar"
    get "tasks/graph"
    resources :tasks do 
      patch :sort
    end
    resources :groups do 
      patch :sort
    end  
  end  

  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NextToDo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <nav class="navbar navbar-inverse">
      <ul class="nav navbar-nav">
        <li><%= link_to("Next To Do -Admin-", admin_users_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("User Modeへ", user_tasks_path) %></li>
        <li>
          <%= link_to(edit_user_path(@current_user)) do %>
            <%= image_tag @current_user.image.url, class: "navbar_user-image" %>
          <% end %>  
        </li>
        <li><%= link_to("ログアウト", "/logout", method: :post) %></li>
      </ul>
    </nav>
  </header>

  <body>
    <% if flash[:notice].present? %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div> 
    <% end %>
    <% if flash[:alert].present? %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>  
    <% end %>
    <%= yield %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
  <script type="text/javascript">
  </script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NextToDo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <header>
    <% if @current_user %>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
        <li><%= link_to("Next To Do", user_tasks_path, class: "navbar-brand") %></li>
        <li>
          <%= link_to(user_tasks_calendar_path) do %>
            <i class="fa fa-calendar" style="font-size: 18px"></i>
          <% end %>
        </li>
        <li>
          <%= link_to(user_tasks_graph_path) do %>
            <i class="fa fa-pie-chart" style="font-size: 18px"></i>
          <% end %>  
        </li>
        <li>
          <%= link_to(user_groups_path) do %>
            <i class="fa fa-group" style="font-size: 18px"></i>
          <% end %>
        </li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user.admin? %>
          <li><%= link_to("Admin Modeへ", admin_users_path) %></li>
        <% end %>  
        <li>
          <%= link_to(edit_user_path(@current_user)) do %>
            <%= image_tag @current_user.image.url, class: "navbar_user-image" %>
          <% end %>  
        </li>
        <li><%= link_to("ログアウト", "/logout", method: :post) %></li> 
      </ul>
    </nav>
    <% end %>
  </header>

  <body>
    <% if flash[:notice].present? %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div> 
    <% end %>
    <% if flash[:alert].present? %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>  
    <% end %>
    <%= yield %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
  <script type="text/javascript">
  </script>
</html>